#!/bin/bash

# install docker and docker-composer
wget -qO- https://get.docker.com/ | sh
curl -L https://github.com/docker/compose/releases/download/1.3.1/docker-compose-`uname -s`-`uname -m` > docker-compose
sudo mv docker-compose /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
sudo docker run --rm hello-world

# get taiga-docker
git clone https://github.com/fjmk/taiga-docker.git
cd taiga-docker/
git checkout feature/nginx-proxy 

# start jwilder/nginx-proxy
sudo docker-compose -f nginx-proxy.yml up -d

# build taiga-front-dist and taiga-back
sudo docker-compose -f taiga.yml build

# start all containers
sudo docker-compose -f taiga.yml up -d

# initialize database
sudo docker exec -t taigadocker_taigaback_1 /usr/local/taiga/initdb

