#!/bin/bash
cd /usr/local/taiga/taiga-back/
pip install -r requirements.txt
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
# python manage.py sample_data
python manage.py migrate taiga_contrib_letschat
python manage.py makemigrations
python manage.py migrate
